my_file = open('test2.txt', 'r')
content = my_file.read()
print('Содержимое файла:\n', content)
my_file = open('test2.txt', 'r')
content = my_file.readlines()
print('Количество строк -', len(content))
my_file = open('test2.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print('Количество символов', i + 1, '-ой строки -', len(content[i]))
my_file = open('test2.txt', 'r')
content = my_file.read()
content = content.split()
print('Количество слов -', len(content))
my_file.close()